# Generated by Django 5.1 on 2025-02-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_for_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplanetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('source', 'destination'), name='unique_route'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'flight'), name='unique_ticket'),
        ),
    ]
